name: VAINGLORY LOVE
favicon: null
layout_spectrum: 0.8753436377737671
typography_spectrum: 0.18528840318322182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0021160393953323364
  lightness: 0.5293593422975391
  saturation: 0.9576747776009142
  rhythmicContrast: 0.6902308892458677
purpose: []
